app = "democue"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile.web"

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  DJANGO_SETTINGS_MODULE = "democue.settings_production"
  PORT = 8080

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  web = "gunicorn --bind 0.0.0.0:8080 --workers 1 --threads 8 --timeout 0 democue.wsgi:application"
  worker = "celery -A democue worker -l INFO --beat --concurrency 2"

[[services]]
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
      X-Forwarded-Proto = "https"
      Host = "localhost:8000"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
