default_context:
  _pegasus_version: 2023.4.2
  author_name: C
  ci: github_actions
  css_framework: bootstrap
  css_theme: default
  database: postgres
  deploy_platform: fly
  description: The most amazing SaaS application the world has ever seen
  domain_name: localhost:8000
  email: email@ctoddlombardo.com
  enable_google_login: n
  enable_twitter_login: n
  front_end_framework: htmx
  post_process: y
  project_name: Democue
  project_slug: democue
  stripe_payment_mode: checkout
  subscription_billing_model: per_unit
  use_2fa: y
  use_api_keys: y
  use_cloud_media_storage: n
  use_debug_toolbar: n
  use_docker: y
  use_examples: y
  use_impersonation: y
  use_openai: n
  use_sentry: n
  use_subscriptions: y
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: n
